# Generated by Django 4.1.7 on 2023-05-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
