# Generated by Django 4.1.7 on 2023-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
