# Generated by Django 4.1.7 on 2023-05-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.BigIntegerField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
