# Generated by Django 4.1.7 on 2023-05-12 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_employee_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_number',
            new_name='employee_id_num',
        ),
        migrations.RenameField(
            model_name='facesdb',
            old_name='employee_number',
            new_name='employee_id_num',
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('employee_id_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
